"""add payment metadata

Revision ID: 0646027af662
Revises: e9b83c0016d5
Create Date: 2026-08-27 02:59:29.829111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0646027af662'
down_revision = 'e9b83c0016d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ledger_entries', sa.Column('memo', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False))
    op.add_column('transactions', sa.Column('payer_account_id', sa.String(), nullable=False))
    op.add_column('transactions', sa.Column('payee_account_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'transactions', 'accounts', ['payer_account_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'accounts', ['payee_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'payee_account_id')
    op.drop_column('transactions', 'payer_account_id')
    op.drop_column('transactions', 'amount')
    op.drop_column('ledger_entries', 'memo')
    # ### end Alembic commands ###
