"""make account owner unique

Revision ID: d6cac656cf8a
Revises: 0646027af662
Create Date: 2026-08-27 03:03:00.091796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6cac656cf8a'
down_revision = '0646027af662'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
